### ISSUE TITLE
Release Java Filebeat Server code into Maven Central

### ISSUE THREAD

**Issue by moribellamy** [logstash-plugins/logstash-input-beats#144]
https://github.com/logstash-plugins/logstash-input-beats/tree/master/src/main/java/org/logstash/beats

It seems like this will grow to be the code that logstash uses to listen for filebeat data. Would be great to share this code to maven central so that other developers can ingest filebeat data directly into their Java application.

**Comment by suyograo** [comment]
Hi @moribellamy thanks for raising this issue. 

The Beats protocol (the successor of Lumberjack) and it's Java implementation is still under active development as we work on integrating multiple (new) Beats with Logstash. As such, there may be breaking changes and bugs which may annoy external consumers and put pressure on us as maintainers. We think it is premature at this point to publish the protocol implementation as a standalone library (maven) for external consumption. Also, we haven't heard many of these requests since integrating Logstash with Beats already provides a wide variety of outputs that Beats' data can reach to.

**Comment by trixpan** [comment]
+1 on this...

**Comment by fbacchella** [comment]
I have started to work on it, see #325.
