### ISSUE TITLE
The host setting seems to not have any effect

### ISSUE THREAD

**Issue by neuroid** [logstash-plugins/logstash-input-beats#146]
- Version: 3.1.3 (bundled with logstash 2.4.0)
- Operating System: Debian Jessie

My config looks like this:

```
input {
  beats {
    host => "127.0.0.1"
    port => 5044
  }
}
```

Running with `--debug` shows:

```
[snip]
config LogStash::Inputs::Beats/@host = "127.0.0.1" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
config LogStash::Inputs::Beats/@port = 5044 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
[snip]
Beats inputs: Starting input listener {:address=>"127.0.0.1:5044", :level=>:info, :file=>"logstash/inputs/beats.rb", :line=>"153", :method=>"register"}
[snip]
```

However, when I check the listening sockets I get:

```
# netstat -pan | grep java | grep LISTEN
tcp        0      0 0.0.0.0:5044            0.0.0.0:*               LISTEN      18247/java
```

**Comment by ph** [comment]
I Will take a look

**Comment by ph** [comment]
I can confirm its a bug, 

instead of `bind(port)` it should use `bind(String inetHost, int inetPort)`

**Comment by bkuberek** [comment]
Sorry to poke this thread but I am having an issue with the beats plugin not listening on port 5044 as well. Is this bug affecting version 2.3.0 (Mar 29, 2016) ?

Thanks

**Comment by ph** [comment]
This issue was about 2.4.0 which included the java rewrite of the beat input.

@bkuberek 2.3.0 was shipped with an older version of beats which was written in ruby at that time, 3.0.4 ? or something close.

by looking at the code the server accepts an address: https://github.com/logstash-plugins/logstash-input-beats/blob/v3.0.4/lib/lumberjack/beats/server.rb#L51  and the input pass that value to the library.

So I think it should be fine.

You can connect that port? Anything in the log?

**Comment by bkuberek** [comment]
@ph Turns out we had a syntax error in the logstash configuration and the service kept restarting. After we fixed that it's all good. Thank you for taking the time to answer my question. I really appreciate it.

Best,

Bastian
