### ISSUE TITLE
gemspec doesn't require concurrent-ruby version 0.9.1

### ISSUE THREAD

**Issue by jalberto** [logstash-plugins/logstash-input-beats#17]
https://github.com/logstash-plugins/logstash-input-beats/blob/master/logstash-input-beats.gemspec#L25

s.add_runtime_dependency "concurrent-ruby"

This will install latest version (0.9.2 right now) but logstash requires 0.9.1 causing:

```
RuntimeError: Logstash expects concurrent-ruby version 0.9.1 and version 0.9.2 is installed, please verify this patch: /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/patches/silence_concurrent_ruby_warning.rb
```

**Comment by ph** [comment]
This is because you are running JDK7 and we have a patch that silence some deprecation warning in concurrent-ruby 0.9.1 and the patch sadly fails with concurrent-ruby 9.2 which we shipped by mistake with logstash 1.5.5 and 2.0

https://github.com/elastic/logstash/pull/4141 explain the issue and this PR
https://github.com/elastic/logstash/pull/4146 solve that problem.

I am closing this issue since its related to core.

**Comment by ph** [comment]
@jalberto When do get this error? When you install the plugin? Which version of logstash you are running?

**Comment by jalberto** [comment]
thanks @ph 

as a workaround if someone lands here: reinstall logstash, reinstall plugins

**Comment by jalberto** [comment]
@ph I'm in LS 2.0 (.deb) it happened after install and then update this plugin (using plugin command)

**Comment by ph** [comment]
OK thanks for confirming it, We will need to release a 2.0.1 with that fix.
