### ISSUE TITLE
Reject configuration with 'multiline' codec

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-beats#201]
related: https://github.com/logstash-plugins/logstash-input-beats/issues/199

Filebeat has multiline support, and so does Logstash. This confuses users with both choice and behavior.

Behaviors that can go wrong if you use filebeat to logstash with logstash beats input using multiline codec:

For example, If the user configures Logstash to do multiline assembly, and filebeat is not, then it is possible for a single stream (a single file, for example) to be spread across multiple Logstash instances, making it impossible for a single Logstash to reassemble.

The spread, above, can happen in at least two scenarios:
* filebeat configured without multiline and with load balancing that it spreads events across different Logstash nodes
* filebeat configured without multiline and without load balancing, a multiline event will still be multiple events within a stream, and that can be split across multiple batches to Logstash, and a network interruption will disrupt the continuity of that stream (again, only without multiline on filebeat)

For this reason, we should configure Logstash to reject the `multiline` codec with an actionable error to the user indicating that the correct way to use multiline with beats is to configure filebeat to do the multiline assembly.

**Comment by jakelandis** [comment]
{quote}
with an actionable error to the user 
{quote}

Proposed wording in [PR](https://github.com/logstash-plugins/logstash-input-beats/pull/206/files#diff-28d8b79a78399c1304c58e81cd3672f2R152):
{quote}
Multiline codec with beats input is not supported. Please refer to the beats documentation for how to best manage multiline data. See https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html
{quote}

 Since this impacts all beats, not just filebeat, I kept the wording general, but linked to the filebeat doc.  Not sure if it is safe to link error messages to doc. 

Also, 
We will want to update the following documentation: 
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html#plugins-inputs-beats-codec

and possibly all the places referenced on :
https://github.com/logstash-plugins/logstash-input-beats/issues/199

(how do I log documentation issues ?)

**Comment by ph** [comment]
> Multiline codec with beats input is not supported. Please refer to the beats documentation for how to best manage multiline data. See https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html

+1 for wording

> Since this impacts all beats, not just filebeat, I kept the wording general, but linked to the filebeat doc. Not sure if it is safe to link error messages to doc.

I am okay to keep the wording general, in the real world this only really affect filebeat sources.

> We will want to update the following documentation:
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html#plugins-inputs-beats-codec

This will be a bit problematic, since the codec part *will get included* from a static file in the main repo. https://github.com/elastic/logstash/pull/6941/files#diff-00c8b34f204b024929f4911e4bd34037R31

Maybe we could add a paragraph in the plugin description concerning doing multiline at the source? In this file https://github.com/logstash-plugins/logstash-input-beats/blob/master/docs/index.asciidoc

**Comment by ph** [comment]
For the other documentation changes lets file up a new issue on the main logstash repository and include @dedemorton in the discussion.

**Comment by acchen97** [comment]
@jakelandis FYI the only Beat that utilizes multiline is Filebeat, so we can be explicit in stating that.
