### ISSUE TITLE
Deploy to maven central.

### ISSUE THREAD

**Issue by jcustenborder** [logstash-plugins/logstash-input-beats#271]
What are the thoughts about deploying this jar to Maven Central?

**Comment by jakelandis** [comment]
It wouldn't be very useful at the moment since beats input still requires Ruby to integrate with Logstash.  The jar is currently embedded as part of the gem and published on Rubygems.org. 

Pure Java plugins are on the roadmap, and those will likely end up Maven Central. (but it will probably be a while)

I am going to close the issue, please re-open if I am missing some context.

**Comment by jcustenborder** [comment]
Is there anything that I could do to help with this effort? I'm interested
in some of the netty functionality. I'd be interested in helping with a
client as well.

**Comment by jakelandis** [comment]
@jcustenborder 
 
> Is there anything that I could do to help with this effort?

Assuming you mean the pure Java plugins... we started some design discussions over at https://github.com/elastic/logstash/issues/7986 , it is still really early (e.g. not much tangible yet), but once we get something solid we will certainty want feedback from Java devs familiar with Logstash. 

>  I'd be interested in helping with a client as well.

Not sure I follow... a client for ?

**Comment by fbacchella** [comment]
Works started at: https://github.com/fbacchella/netty-beats. It contains only the java part, so it can be used in any netty application. There is only a beats client. Maven publication is on the pipe.
