### ISSUE TITLE
The parameter id don't work

### ISSUE THREAD

**Issue by Rmond** [logstash-plugins/logstash-input-beats#313]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version: logstash 6.2.2
- Operating System: centos7.4
- Config File (if you have sensitive info, please remove it):
input {
      beats {
        id => "my_plugin_id"
        port => 5044
      }
}
- Sample Data:

- Steps to Reproduce:
when i select data from es, No ID information

**Comment by jakelandis** [comment]
@Rmond - the `id` is meta-data about the pipeline, it is used to help identify which piece of the pipeline for monitoring or other pipeline specific things.  If you want the id to be in the document that is searchable in elasticsearch, I would suggest to use a tag:

```
input {
  beats {
    id => "my_plugin_id"
    port => 5044
    tags => ["my_plugin_id"] 
  }
}
```

Closing the issue, since this isn't a bug.
