### ISSUE TITLE
Clarify use of TCP or UDP

### ISSUE THREAD

**Issue by markwalkom** [logstash-plugins/logstash-input-beats#39]
[Here](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-details.html#_tls_2) we mention;
> Logstash must also be configured to use TCP for Logstash input.

While [here](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html) we don't mention anything.

It'd be worth further clarifying that filebeat uses TCP only to ensure delivery, rather than having it as a footnote.

**Comment by tsg** [comment]
CC-ing @dedemorton  and @urso 

I'm not sure what's the intention behind that note in the Filebeat docs. logstash-input-beats is always over TCP, right?

**Comment by ph** [comment]
its always over TCP, encypted or not.

**Comment by dedemorton** [comment]
@tsg I don't know, either. It looks like that info has been around for awhile...not sure where it came from. So it sounds like I should remove the line, "Logstash must also be configured to use TCP for Logstash input" from the Beats doc, right?

I wonder if we even need to mention TCP in the Beats doc (then we could avoid describing how TCP is used--which to me seems like an implementation detail that users don't need to know...or do they?). Would it be better to say, "If the tls section is missing, the connection is unsecured."?

**Comment by markwalkom** [comment]
FYI I also raised this here - https://github.com/elastic/beats/issues/668

**Comment by jordansissel** [comment]
Agreed it's confusing to mention TCP at all. The connection to Logstash is via beats input, and I think that's all we need to mention. We can say the protocol runs over TCP if folks need to know that for firewall rules, but beyond that I think saying "Needs to use TCP" is confusing because there's no other option ;P

**Comment by tsg** [comment]
Reading that again, I think what should have been written is along the lines of "If TLS is used, the beats plugin in Logstash must also be configured to use TLS.".

It's a good point that we should somewhere mention in the docs that we use TCP, since it can be useful information for some people, but probably in the introductory paragraphs for the Logstash output, not in the tls section :-).

**Comment by dedemorton** [comment]
@tsg Made your changes to the Beats doc. I don't think any changes are really required to the doc for the Beats input plugin. WDYT?

**Comment by tsg** [comment]
Thanks @dedemorton, I just merged that one. @ph @jordansissel I don't have the rights to close the ticket, can you do it if you agree?

**Comment by jordansissel** [comment]
Closing <3

**Comment by pixelrebel** [comment]
I am trying to set up a reverse proxy for my logstash server.  I needed to verify if beats uses TCP.  This issue page was the only place I found that explicitly says that filebeats uses a TCP based protocol.

**Comment by dedemorton** [comment]
@pixelrebel The Filebeat documentation explicitly states that Filebeat uses TCP: https://www.elastic.co/guide/en/beats/filebeat/1.2/logstash-output.html

**Comment by pixelrebel** [comment]
Thanks @dedemorton, looks like I have bad google-fu.  `filebeat protocol` and `filebeat tcp` don't turn up much in google.
