### ISSUE TITLE
When `ssl_certificate_authorities` provided, `ssl_verify_mode => none` is ignored.

### ISSUE THREAD

**Issue by yaauie** [logstash-plugins/logstash-input-beats#399]
Follow-up to #300, which was closed and defined this as desired behaviour:

> The act of setting `certificate_authorities` should be an expression by the user/operator that they _want_ to only accept trusted clients. Maybe we need to improve the wording/docs here?
> 
> Alternately, why would you set `ssl_verify => none` _and_ also set _[`ssl_certificate_authorities`]_ ? Why would you say "Trust the things in _[`ssl_certificate_authorities`]_" but then tell the plugin to ignore trust relationships? What's the use case and intent?
>
> -- https://github.com/logstash-plugins/logstash-input-beats/issues/300#issuecomment-365687897

We need to make this experience better for our users.

### Option 1:

 - Reject `ssl_verify => none` when `ssl_certificate_authorities` is provided.

### Option 2:

 - WARN when encountering `ssl_verify => none` when `ssl_certificate_authorities` is provided.
 - Document that the setting is ignored in some cases (and define which specific cases).

**Comment by jsvd** [comment]
> Alternately, why would you set ssl_verify => none and also set [ssl_certificate_authorities] ? Why would you say "Trust the things in [ssl_certificate_authorities]" but then tell the plugin to ignore trust relationships? What's the use case and intent?

I understand the argument, however the issue is that we default the verify mode to "force_peer" in the [SslContextBuiilder](https://github.com/logstash-plugins/logstash-input-beats/blob/master/src/main/java/org/logstash/netty/SslContextBuilder.java#L38). This means that `ssl_verify => none` with ssl_certificates_authorities will be stricter than setting `ssl_verify => peer`.

So I'm +1 on adding a warning for now and then going for Option 1 in a next major.
