### ISSUE TITLE
Add integration test for LSF to beats input

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-input-beats#52]
Discussed with @jordansissel earlier.  He likes the idea of officially supporting LSF -> LS beats input to ease migration.  He has tested this briefly before and it works because LSF and beats use the same underlying protocol, but would like to see us add integration tests so that we can officially confirm and document it as a supported path.

**Comment by ruflin** [comment]
@ppf2 Can you give some insights on how this would simplify the migration to filebeat?
@ph I would be somehow surprised if this still works as we changed the format to JSON?

**Comment by jordansissel** [comment]
@ruflin the format beats uses is indeed JSON, and it uses a frame header of `2J` in the protocol. The old `1D` frame is still supported by the beats input. In implementation, it does work, as I have tested and saw some nice happy events going through  from LSF to beats input.

Use case: Make it easier to upgrade from LSF to Beats.
Constraints: Opening an additional network path to a new port may be difficult
Constraint example: For some organizations for a variety of reasons, such as team isolation and siloing. It could require approval and significant political maneuvering to achieve this across multiple teams - from network operations, infosec, and IT/sysadmin groups - in order to get an additional network path (port) from machines running lsf/beats to Logstash.

If we can promise that the beats input will support the LSF protocol, at least until LSF is EOL, then using a single beats input for both lsf and beats could be help users with the above constraints upgrade from lsf to filebeat.

**Comment by ph** [comment]
@ruflin It work, but we don't advertise it.

**Comment by ph** [comment]
I have added some test in #56 to cover LSF, but they are failling will do another PR to fix them.
Some issue when communicating with the LSF process.
