### ISSUE TITLE
type field not being used

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-input-beats#55]
Tested using LS 2.2.2's beat input.

```
input {
  beats {
    port => 5044
	type => "beats"
  }
}
```

The type field specified is not being honored.

https://www.elastic.co/guide/en/logstash/2.2/plugins-inputs-beats.html#plugins-inputs-beats-type

When sending events from the filebeat, it retains the default "log" value as the type value even though type is set to "beats" in the LS beat input.

To get this to work, I ended up setting document_type at the beats level, and just let it pass all the way through to the LS pipeline.

```
      # Type to be published in the 'type' field. For Elasticsearch output,
      # the type defines the document type these entries should be stored
      # in. Default: log
      document_type: my_beats_type
```

Not sure if this is the intended behavior (LS beats input ignores its type parameter), if so, let's update our documentation accordingly.

**Comment by andrewkroh** [comment]
I think that is the intended behavior.

The documentation for [type](https://www.elastic.co/guide/en/logstash/2.2/plugins-inputs-beats.html#plugins-inputs-beats-type) states:

> If you try to set a type on an event that already has one (for example when you send an event from a shipper to an indexer) then a new input will not override the existing type. A type set at the shipper stays with that event for its life even when sent to another Logstash server.

**Comment by ppf2** [comment]
Somehow I missed that paragraph :)  Yah, will be helpful to clarify in the doc that the type parameter for the beats input will never be used since it is always set in the beat (and to use document_type in the beats configuration instead).

**Comment by andrewkroh** [comment]
There have been numerous users on Discuss that try to use `type => "xyz"` in their beat input config, and then they write conditional logic based on the `type` field that does not work as expected. 

They always miss the note in the docs or never saw it. Since `type` is a required field that is enforced by libbeat, can we just remove the `type` option from the beats input?

These are few examples where this has occurred:

https://discuss.elastic.co/t/winlogbeat-event-tagging-and-overriding-type-in-logstash/42539
https://discuss.elastic.co/t/logstash-lost-eventlog-from-winlogbeat/55360
https://discuss.elastic.co/t/topbeat-with-redis/34157
https://discuss.elastic.co/t/how-to-tag-log-files-in-filebeat-for-logstash-ingestion/44713/5
https://discuss.elastic.co/t/winlogbeat-not-outputting-to-logstash/57500/6

**Comment by iceiilin** [comment]
Encountered the same problem. @dedemorton , I saw that you contribute a lot to logstash-docs repo, so am wondering if there is any chance to help removing the misleading "type" description for beats plugin in the docs?

**Comment by dedemorton** [comment]
@iceiilin I'll look into it. The problem is that the `type` option is inherited and shared by other plugins, so the description is somewhat generic. I'll see if we can override the description or at least make it more clear in the introductory content that the option is ignored.

**Comment by dedemorton** [comment]
Clarified in the doc that type setting is ignored. See PR #121

**Comment by iceiilin** [comment]
Great! Thanks.
